name: continuous-pathogenicity
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy=1.23.*
  - pandas=2.2.*
  - scikit-learn=1.6.*
  - matplotlib=3.9.*
  - seaborn=0.13.*
  - scipy=1.15.*
  - notebook
  - biopython
  - requests